media-libs/x264: Fix building with lto-overlay

diff --git a/media-libs/x264/files/x264-0.0.20190903-STRINGS.patch b/media-libs/x264/files/x264-0.0.20190903-STRINGS.patch
--- a/media-libs/x264/files/x264-0.0.20190903-STRINGS.patch
+++ b/media-libs/x264/files/x264-0.0.20190903-STRINGS.patch
@@ -22,7 +22,7 @@ This allows building x264 on systems where 'strings' or
 @@ -1017,10 +1018,10 @@ CPU_ENDIAN="little-endian"
  if [ $compiler = GNU ]; then
      echo "int i[2] = {0x42494745,0}; double f[2] = {0x1.0656e6469616ep+102,0};" > conftest.c
-     $CC $CFLAGS conftest.c -c -o conftest.o 2>/dev/null || die "endian test failed"
+     $CC $CFLAGS conftest.c -o conftest.o -shared 2>/dev/null || die "endian test failed"
 -    if (${cross_prefix}strings -a conftest.o | grep -q BIGE) && (${cross_prefix}strings -a conftest.o | grep -q FPendian) ; then
 +    if (${STRINGS} -a conftest.o | grep -q BIGE) && (${STRINGS} -a conftest.o | grep -q FPendian) ; then
          define WORDS_BIGENDIAN
